### ISSUE TITLE
Static sharding fleets for Status Communities

### ISSUE THREAD

**Issue by jm-clius** [status-im/infra-status#2]
## Requirements

- Two fleets of at least five nodes each:
  - `status.sharding.store`: 5 nodes configured only with `relay` and `store`. These will be the store/historical message providers
  - `status.sharding.bootstrap`: 5 nodes configured with `relay`, `filter`, `lightpush`, `peer-exchange`. These are the main bootstrap nodes and also provide services to resource-restricted nodes
  
### Configuration common to both fleets:

- both fleets should use [`wakuv2.shards` as inspiration](https://github.com/status-im/infra-nim-waku/blob/master/ansible/group_vars/wakuv2-shards.yml)
- all nodes in both fleets should be configured _only_ for the Status Internal CC Community static shards with each topic also set up as a "protected topic" with public key. Set out below:

**Pubsub Topics**

```
--pubsub-topic=/waku/2/rs/16/128
--pubsub-topic=/waku/2/rs/16/256
```

**Protected Topics**

```
--protected-topic=/waku/2/rs/16/128:045ced3b90fabf7673c5165f9cc3a038fd2cfeb96946538089c310b5eaa3a611094b27d8216d9ec8110bd0e0e9fa7a7b5a66e86a27954c9d88ebd41d0ab6cfbb91
--protected-topic=/waku/2/rs/16/256:049022b33f7583f34463f5b7622e5da29f99f993e6858a478465c68ee114ccf142204eff285ed922349c4b71b178a2e1a2154b99bcc2d8e91b3994626ffa9f1a6c
```

- no websocket configuration on either fleet for now

## Configuration for `status.sharding.bootstrap`

- mounted protocols: `relay`, `filter`, `lightpush`, `peer-exchange` (_no_ `store`)
- own DNS node list deployed with `enrtree:` URL
- `nim_waku_dns_disc_url` points to own DNS node list
- no websocket configuration
- pubsub topics and protected topics set up as described above
- 1 node in this fleet should preferably be set up with trace-level message logs, in order to facilitate future end-to-end message tracing and debugging

## Configuration for `status.sharding.store`

- mounted protocols: `relay`, `store`
- own DNS node list deployed with `enrtree:` URL
- `nim_waku_dns_disc_url` points to `status.sharding.bootstrap` DNS node list (NB)
- store nodes set up with a single, shared PostgreSQL backend

**Comment by yakimant** [comment]
@richard-ramos, @jm-clius, quick question:
why do we need an `enrtree` DNS record for `storage` nodes if it is not referenced?
Both `bootstrap` and `storage` nodes reference `bootstrap` node list as I understand.

**Comment by jm-clius** [comment]
> why do we need an enrtree DNS record for storage nodes if it is not referenced?
Both bootstrap and storage nodes reference bootstrap node list as I understand.

Correct. I think it is so that Community Nodes can reference the store nodes separately from the bootstrap nodes.

**Comment by jakubgs** [comment]
Hanno adds:

>My understanding from Richard is: they bootstrap against a list of nodes and they create a set of store nodes from a different list (in fact, they hard-code this store list currently, but should do a separate lookup to populate this dynamically). If the store nodes are mixed into the bootstrap list, they will automatically form part of the bootstrap process which we'd like to avoid to create a better separation of interests in the fleet services.

**Comment by yakimant** [comment]
@jm-clius, @Ivansete-status,
Please have a look if you can start using fleet for testing already.

What is missing:
- PosrgreSQL metrics scraping and Grafana dashboard
- `postgresql.conf` configuration, default is used

**Comment by richard-ramos** [comment]
@yakimant what is the dns discovery addresses for this fleet?

**Comment by richard-ramos** [comment]
nvm. Saw the README.md :)

**Comment by Ivansete-status** [comment]
I validated that the next hosts have both `relay` and `store` properly configured. Amazing work @yakimant !

```
/dns4/store-01.do-ams3.shards.test.statusim.net/tcp/30303/p2p/16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT
/dns4/store-02.do-ams3.shards.test.statusim.net/tcp/30303/p2p/16Uiu2HAm9aDJPkhGxc2SFcEACTFdZ91Q5TJjp76qZEhq9iF59x7R
/dns4/store-01.gc-us-central1-a.shards.test.statusim.net/tcp/30303/p2p/16Uiu2HAmMELCo218hncCtTvC2Dwbej3rbyHQcR8erXNnKGei7WPZ
/dns4/store-02.gc-us-central1-a.shards.test.statusim.net/tcp/30303/p2p/16Uiu2HAmJnVR7ZzFaYvciPVafUXuYGLHPzSUigqAmeNw9nJUVGeM
/dns4/store-01.ac-cn-hongkong-c.shards.test.statusim.net/tcp/30303/p2p/16Uiu2HAm2M7xs7cLPc3jamawkEqbr7cUJX11uvY7LxQ6WFUdUKUT
/dns4/store-02.ac-cn-hongkong-c.shards.test.statusim.net/tcp/30303/p2p/16Uiu2HAm9CQhsuwPR54q27kNj9iaQVfyRzTGKrhFmr94oD8ujU6P
```

To test it, I followed the next steps:

1. Start a `nwaku` node locally, setting `staticnode` and `storenode` to the first node from previous list. With that, I established the remote `relay` and `store` peer, respectively.

   i. Then, I made my local node to publish a few messages by sending json-rpc requests to my local node.

   ii. Then, I made a store request to my local node, through json-rpc, and in turn my local node made a _Store_ request to the remote node. Then, the json-rpc command returned the messages stored by the *F1EfT peer.

3. I repeated the step 1.ii. with the rest of the nodes. In all cases, the stored messages where properly received. Indicating that all the nodes are relay-connected among them, and also, all properly handle _Store_ requests.

Notes:
  - I run the `wakunode2` with the next command: `./build/wakunode2 --config-file=cfg_node_a.txt`, and I've been editing the config file to follow the above steps. 
[cfg_node_a.txt](https://github.com/status-im/infra-shards/files/12805775/cfg_node_a.txt)

  - This is the command I used to publish messages:
   `curl -d "{\"jsonrpc\":\"2.0\",\"id\":"$(date +%s%N)",\"method\":\"post_waku_v2_relay_v1_message\", \"params\":[\"/waku/2/rs/16/64\", {\"contentTopic\": \"jamon\", \"timestamp\":"$(date +%s%N)", \"payload\":\"cmFuZG9tCg==\"}]}" --header "Content-Type: application/json" http://localhost:8546`

  - This is the command I used to make my local node retrieve the stored messages:
  `curl -d '{"jsonrpc":"2.0","id":"id","method":"get_waku_v2_store_v1_messages"}' --header "Content-Type: application/json" http://localhost:8546`

cc: @jm-clius

**Comment by yakimant** [comment]
I can see messages in db:
```
nim-waku=> select id from messages;
                                id
------------------------------------------------------------------
 2be984aa463c976553b7ab089c6708fa97509449f7359693ae98665fecb1a652
 2be984aa463c976553b7ab089c6708fa97509449f7359693ae98665fecb1a652
 2be984aa463c976553b7ab089c6708fa97509449f7359693ae98665fecb1a652
 f0f81dd5f875ebac8402617ac0c3cd0e7b0c72de4e23cacd23fc7362aacd8b77
(4 rows)
```

**Comment by jm-clius** [comment]
Great, I think further dogfooding on this fleet can continue. @richard-ramos

**Comment by jm-clius** [comment]
@yakimant I think we can close this issue and raise any further problems/issues separately. The bulk of the work here has been done. Thanks for your excellent work here!
