### ISSUE TITLE
Rename shards fleets to status fleet, including tests to prod

### ISSUE THREAD

**Issue by fryorcraken** [status-im/infra-status#33]
The present shards fleets (`shards.test` and `shards.staging`) are now the sole Waku (v2) fleets used by Status applications.

Their names should be changed to reflect their usage.

## `shards.test`

`shards.test` fleet is used as the default setting for Status Desktop and Status Mobile beta releases.
Status teams has asked to consider this fleet as an end user facing fleet.
Hence, proposed new name is `status.prod`

## `shards.staging`

`shards.staging` is used for staging purposes for Status application.
Hence, proposed new name is `status.staging`

## Process

Proposed process to proceed with renaming with minimal effort and disruption.

1. Setup new DNS entries for existing hosts (e.g. `boot-01.gc-us-central1-a.shards.test.status.im` gets _additional_ DNS `boot-01.gc-us-central1-a.status.prod.status.im`)
2. Generate new SSL cert for 1 **store** node
3. Change `websocket-secure*` parameters to new cert for this one store node
4. Change Status web app to only use the store node with the new SSL cert (Status web team)
5. Generate new SSL cert for all nodes
6. Setup new DNS TXT record including ENR tree with new domain names (new domain in both wss and dns4 fields of the ENRs)
7. Change Status web app to use new DNS TXT for DNS discovery (Status web team)
9. Update `dns4-domain-name` to new domain name
10. Replace hardcoded domain for DNS discovery in Status Mobile & Desktop apps (Waku chat team)
    (e.g. from `enrtree://AMOJVZX4V6EXP7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.test.shards.nodes.status.im` to `enrtree://AMOJVZX4V6EXP7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.prod.status.nodes.status.im`)
11. Wait until latest Status release with old domain name can be considered unsupported (3 months?)
12. Deregister old DNS TXT and old domain names

Note: steps 3-4, 6 can be skipped for `shards.staging`

### Steps 3-4, 6: Status web apps 

I believe Status web apps only use store services, @prichodko please confirm.

### Step 8: `dns4-domain-name` behaviour

Need to ensure that clients (Status application) can still connect to nwaku node when:
- client uses old domain name (e.g. `boot-01.gc-us-central1-a.shards.test.status.im` in multiaddr)
- nwaku node is configure with new domain name (e.g. `dns4-domain-name=boot-01.gc-us-central1-a.status.prod.status.im`)

@Ivansete-status please confirm/schedule test

**Comment by jakubgs** [comment]
Some questions:

- I think you meant `boot-01.gc-us-central1-a.status.prod.status.im` in point number 1, right?
- When you say "Generate new SSL cert for 1 store node" you mean one for both domains right?
- I think points 6 and 7 are flipped around. I need to create ENRTree DNS records first to then use them.
- Have we confirmed that changing `dns4-domain-name` will not break access via old domain?

**Comment by Ivansete-status** [comment]
> @Ivansete-status please confirm/schedule test

Thanks for that! The naming makes sense to me. I'm happy to help with the tests.

I think we will need to have the following additional steps as well:

12. Rename the `infra-shards` repo to `infra-status` ( https://github.com/status-im/infra-status-legacy could serve as a reference of what we had .)
13. Review all the current opened _GitHub_ issues that refer to `status.test` and indicate that the fleet is now `status.prod`.

( cc @jakubgs )

**Comment by jakubgs** [comment]
Great, apparently IP addresses on Google Cloud cannot be renamed:
https://stackoverflow.com/questions/22687968/rename-reserved-ip-address-in-gce

**Comment by jakubgs** [comment]
It appears renaming Google Cloud instances also will not work:
```
"store-01-gc-us-central1-a-shards-staging" -> "store-01-gc-us-central1-a-status-staging" # forces replacement
```

**Comment by jakubgs** [comment]
I have renamed `shards.staging` to `status.staging` as a test run:

- [`infra-shards#040b9d49`](https://github.com/status-im/infra-shards/commit/040b9d49) - rename shards fleet to status fleet

It's visible at https://fleets.waku.org/ :

![image](https://github.com/status-im/infra-shards/assets/2212681/bdc7538e-e3b9-4e7d-ba81-414c471c5f32)

**Comment by jakubgs** [comment]
Also created the new ENR records:
```
 > ./dnsdisc.py --domain boot.staging.status.nodes.status.im --query-service-name=nim-waku-enr --query-service-id=nim-waku-boot-enr --query-env=status --query-stage=staging   
[INFO] Service found: boot-01.do-ams3.status.staging:nim-waku-boot-enr
[INFO] Service found: boot-01.gc-us-central1-a.status.staging:nim-waku-boot-enr
[INFO] Service found: boot-01.ac-cn-hongkong-c.status.staging:nim-waku-boot-enr
[INFO] Creating record: boot.staging.status.nodes.status.im
[INFO] Creating record: e3d5eet4vapo4tmlywqt2ximhe.boot.staging.status.nodes.status.im
[INFO] Creating record: fdxn3sn67na5dka4j2gok7bvqi.boot.staging.status.nodes.status.im
[INFO] Creating record: hi4d7nhzkwqouqrmn3nr7sjwiy.boot.staging.status.nodes.status.im
[INFO] Creating record: odkcy7sc2ij6dvgfd3rojse2c4.boot.staging.status.nodes.status.im
[INFO] Creating record: wrgrhlrn5c5njfit6tora7finu.boot.staging.status.nodes.status.im
[INFO] URL: enrtree://AI4W5N5IFEUIHF5LESUAOSMV6TKWF2MB6GU2YK7PU4TYUGUNOCEPW@boot.staging.status.nodes.status.im
```
```
 > ./dnsdisc.py --domain store.staging.status.nodes.status.im --query-service-name=nim-waku-enr --query-service-id=nim-waku-store-enr --query-env=status --query-stage=staging   
[INFO] Service found: store-01.do-ams3.status.staging:nim-waku-store-enr
[INFO] Service found: store-02.do-ams3.status.staging:nim-waku-store-enr
[INFO] Service found: store-01.gc-us-central1-a.status.staging:nim-waku-store-enr
[INFO] Service found: store-02.gc-us-central1-a.status.staging:nim-waku-store-enr
[INFO] Service found: store-01.ac-cn-hongkong-c.status.staging:nim-waku-store-enr
[INFO] Service found: store-02.ac-cn-hongkong-c.status.staging:nim-waku-store-enr
[INFO] Creating record: 2nm67iglh6ppy4aynir3imkorm.store.staging.status.nodes.status.im
[INFO] Creating record: 7pitefne2vhtt3wkpetgpoubna.store.staging.status.nodes.status.im
[INFO] Creating record: eembrblqz4pry4bfsbmzqs234u.store.staging.status.nodes.status.im
[INFO] Creating record: fdxn3sn67na5dka4j2gok7bvqi.store.staging.status.nodes.status.im
[INFO] Creating record: peojb44fwdfxs5u2g3jivdwabu.store.staging.status.nodes.status.im
[INFO] Creating record: siuuicuqtrgjkmskhp4mmpzk2q.store.staging.status.nodes.status.im
[INFO] Creating record: store.staging.status.nodes.status.im
[INFO] Creating record: v6wvb5dykwjfkfnkhyiancrnjm.store.staging.status.nodes.status.im
[INFO] Creating record: zxqvul4dly53drx7l74r7ckvfq.store.staging.status.nodes.status.im
[INFO] URL: enrtree://AI4W5N5IFEUIHF5LESUAOSMV6TKWF2MB6GU2YK7PU4TYUGUNOCEPW@store.staging.status.nodes.status.im
```

**Comment by fryorcraken** [comment]
> * I think you meant `boot-01.gc-us-central1-a.status.prod.status.im` in point number 1, right?

Indeed, corrected

> * When you say "Generate new SSL cert for 1 store node" you mean one for both domains right?

Would be get @felicio or @prichodko to clarify how Status web app "discover" waku store node.

The thing is that AFAIK nwaku node only accept one SSL key/cert for wss: https://github.com/status-im/infra-shards/blob/97544ad6345c1f3850c0dd87b640a87f351552cb/ansible/group_vars/boot.yml#L59

So my assumption is:

1. nwaku uses SSL cert for `store-01.do-ams3.shards.test.status.im`
2. Status web app connects to nwaku store node via `store-01.do-ams3.shards.test.status.im` domain: works fine
3. We change nwaku SSL cert to `store-01.do-ams3.status.prod.status.im`
4. Status web app attempts to connect to nwaku store node via `store-01.do-ams3.shards.test.status.im` domain.
5. nwaku replies to TLS handshake with `store-01.do-ams3.status.prod.status.im`
6. Status web app (browser) rejects it, status web app is now broken.

> * I think points 6 and 7 are flipped around. I need to create ENRTree DNS records first to then use them.

Indeed, corrected

**Comment by jakubgs** [comment]
@fryorcraken the certificate is not an issue, we've had support for multiple SANs for a while now, you can see it here:
https://github.com/status-im/infra-shards/blob/97544ad6345c1f3850c0dd87b640a87f351552cb/ansible/group_vars/store.yml#L84-L93
And you can see it in effect on recently renamed `shards.staging` to `status.staging`:
```
 > openssl s_client -showcerts -connect store-01.do-ams3.status.staging.status.im:443 2>/dev/null | openssl x509 -text | grep -e 'Subject: CN =' -e 'DNS:'
        Subject: CN = store-01.do-ams3.status.staging.status.im
                DNS:store-01.do-ams3.shards.staging.status.im, DNS:store-01.do-ams3.status.staging.status.im
```
Have you guys confirmed that there are no issues with the renaming of that fleet?

**Comment by felicio** [comment]
Neither https://github.com/status-im/status-website nor https://github.com/status-im/community-dapp use the discovery protocol but a static list instead. So if the newly named cannot temporarily run alongside the old, then community voting and displaying of the latest profile/community/channel info on preview pages would be affected by the down-time until the list is updated and redeployed – low impact if you ask me.

**Comment by Ivansete-status** [comment]
> Have you guys confirmed that there are no issues with the renaming of that fleet?

@jakubgs - From my side, I think it is fine. I validated the store protocol, through _Status-Desktop_, works correctly in `status.staging`

**Comment by jakubgs** [comment]
@Ivansete-status okay, thanks, but that's not what we need. Have you checked that old addresses using `shards.staging` still work? That's kinds the whole point of this right? To rename it while keeping old addresses working.

**Comment by Ivansete-status** [comment]
> @Ivansete-status okay, thanks, but that's not what we need. Have you checked that old addresses using `shards.staging` still work? That's kinds the whole point of this right? To rename it while keeping old addresses working.

Got it thanks!
After testing with [this](https://github.com/status-im/status-desktop/releases/tag/2.29.0), the `store` and `relay` works well with `shards.staging`.
(Thanks @richard-ramos !)

**Comment by jakubgs** [comment]
Thank you, than I can rename `shards.test` to `status.prod` using the same method.

**Comment by jakubgs** [comment]
Useful examples of fleet renamind:

* https://github.com/status-im/status-go/pull/5500
* https://github.com/status-im/status-desktop/pull/15510

**Comment by jakubgs** [comment]
I have completed the renaming of `shards.test` to `status.prod`:

- [`infra-shards#7df38c14`](https://github.com/status-im/infra-shards/commit/7df38c14) - rename the shards.test fleet to status.prod
- [`infra-shards#b46fe5f4`](https://github.com/status-im/infra-shards/commit/b46fe5f4) - readme: fix ENRTree DNS record for status.prod
- [`infra-shards#eb804532`](https://github.com/status-im/infra-shards/commit/eb804532) - boot,store: fix ENRTree DNS entry for status.prod

![image](https://github.com/user-attachments/assets/078cc38f-75e5-43ba-a30b-f6c891351a5f)

**Comment by jakubgs** [comment]
I've also created the ENR DNS records:
```
 > ./dnsdisc.py --domain boot.prod.status.nodes.status.im --query-service-name=nim-waku-enr --query-service-id=nim-waku-boot-enr --query-env=status --query-stage=prod
[INFO] Service found: boot-01.do-ams3.status.prod:nim-waku-boot-enr
[INFO] Service found: boot-01.gc-us-central1-a.status.prod:nim-waku-boot-enr
[INFO] Service found: boot-01.ac-cn-hongkong-c.status.prod:nim-waku-boot-enr
[INFO] Creating record: ajigxigtsosnwruqupb5twntri.boot.prod.status.nodes.status.im
[INFO] Creating record: boot.prod.status.nodes.status.im
[INFO] Creating record: euegj2d43rx7x2sp77zqwntrsu.boot.prod.status.nodes.status.im
[INFO] Creating record: fdxn3sn67na5dka4j2gok7bvqi.boot.prod.status.nodes.status.im
[INFO] Creating record: ubrih5pcpbb3wz7chykitz6xdm.boot.prod.status.nodes.status.im
[INFO] Creating record: ypke6xl3draaxtu7ouzq4pu224.boot.prod.status.nodes.status.im
[INFO] URL: enrtree://AMOJVZX4V6EXP7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.prod.status.nodes.status.im
```
```
 > ./dnsdisc.py --domain store.prod.status.nodes.status.im --query-service-name=nim-waku-enr --query-service-id=nim-waku-store-enr --query-env=status --query-stage=prod
[INFO] Service found: store-01.do-ams3.status.prod:nim-waku-store-enr
[INFO] Service found: store-02.do-ams3.status.prod:nim-waku-store-enr
[INFO] Service found: store-01.gc-us-central1-a.status.prod:nim-waku-store-enr
[INFO] Service found: store-02.gc-us-central1-a.status.prod:nim-waku-store-enr
[INFO] Service found: store-01.ac-cn-hongkong-c.status.prod:nim-waku-store-enr
[INFO] Service found: store-02.ac-cn-hongkong-c.status.prod:nim-waku-store-enr
[INFO] Creating record: df4k74bvahe3jlo3mbdw2htqmm.store.prod.status.nodes.status.im
[INFO] Creating record: edlpegdcqikd3xf2pqfbcp6n54.store.prod.status.nodes.status.im
[INFO] Creating record: fdxn3sn67na5dka4j2gok7bvqi.store.prod.status.nodes.status.im
[INFO] Creating record: fup366s3rjmnri6gaqzkvzgrym.store.prod.status.nodes.status.im
[INFO] Creating record: hbsdw75fkgcvyax5lvwa4kva7u.store.prod.status.nodes.status.im
[INFO] Creating record: oc3pxrtx3a3twwnymnxykwscfa.store.prod.status.nodes.status.im
[INFO] Creating record: sjgtnwnkxejx3cd7rrbkne3sue.store.prod.status.nodes.status.im
[INFO] Creating record: store.prod.status.nodes.status.im
[INFO] Creating record: znm4akmtjgs2ah7r4cei7ndexe.store.prod.status.nodes.status.im
[INFO] URL: enrtree://AMOJVZX4V6EXP7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@store.prod.status.nodes.status.im
```

**Comment by jakubgs** [comment]
It appears my removal of old `statusim.net` domain from certificate configuration has caused issues for `status-web`:

* https://github.com/status-im/status-web/pull/576#issuecomment-2255423039

I mistakenly assumed it was no longer used after 5 months, but it was.

**Comment by jakubgs** [comment]
I've renamed this repository from `infra-shards` to `infra-status`:

- [`infra-repos#4fa92b0e`](https://github.com/status-im/infra-repos/commit/4fa92b0e) - rename infra-shards repo to infra-status

**Comment by jakubgs** [comment]
Also found an unchanged IPTables firewall rule on AlibabCloud DB host, which I fixed manually.

**Comment by jakubgs** [comment]
I guess this is done since nobody has complained in a while.
