### ISSUE TITLE
Increase the shared memory allowed by docker

### ISSUE THREAD

**Issue by Ivansete-status** [status-im/infra-status#39]
I've come across the following error when trying to perform `VACUUM` in a database:

```bash
nim-waku=# VACUUM (VERBOSE, ANALYZE) public.messages_lookup;

INFO:  vacuuming "nim-waku.public.messages_lookup"
ERROR:  could not resize shared memory segment "/PostgreSQL.160802088" to 490671040 bytes: No space left on device
```

The reason for that is that Docker, by default, reserves 64MB for shared memory but we need to make it larger in our _Postgres_ setup.

To overcome this and possible future issues, I suggest configuring it to 1 GB. For that, we need to have the docker-compose file with sth like:

```bash
version: '3.7'
services:
  db:
    container_name: 'nim-waku-store-db'
    image: 'postgres:15.1-alpine'
    restart: always
    shm_size: '1g'  # Set shared memory size to 1 GB
  ...
  ...
```

**Comment by apentori** [comment]
PRs ready, waiting for approval before applying them.

Should the staging environment have the same value ?

**Comment by Ivansete-status** [comment]
> PRs ready, waiting for approval before applying them.
> 
> Should the staging environment have the same value ?

Good question. Aligned with that, a good approach would be to have the very same hw specs in `status.staging` than in `status.prod`. Sth to consider in a separate PR of course ( wdyt @jakubgs .)

**Comment by jakubgs** [comment]
That kinda sounds like a waste of money to me, we should rather make the config dynamic dependent on memory available.

**Comment by apentori** [comment]
@Ivansete-status I updated the PR to use 1/16th of the memory available on the host, that would be 1 GB for the `prod` env.
Is that good for you ?

**Comment by Ivansete-status** [comment]
> @Ivansete-status I updated the PR to use 1/16th of the memory available on the host, that would be 1 GB for the `prod` env. Is that good for you ?

@apentori - I think that's fine for now yes. We can fine-tune if required in the future. Thanks !

**Comment by Ivansete-status** [comment]
@apentori - after applying the change in `status.staging` I could manually perform the vacuum in the ams database node. Therefore, I think this can be applied into `status.prod` as well. Nevertheless, before applying the change there we need to make sure the _Status_ QA frens are not using them.

**Comment by apentori** [comment]
Deployed on both  environment
